spring.application.name=CART-SERVICE
info.app.name=CART-SERVICE

server.port=8095

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cart_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:akshay}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
